# Generated by Django 3.2 on 2021-05-23 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NseSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client', models.CharField(default=None, max_length=100)),
                ('nse_list', models.CharField(default=None, max_length=100)),
                ('path', models.CharField(max_length=100)),
                ('sender_email', models.CharField(max_length=50)),
            ],
        ),
    ]
